version: '3.9'
services:
  # flask:
  #   build: 
  #     context: ./web
  #     dockerfile: Dockerfile
  #   container_name: flask
  #   restart: unless-stopped
  #   env_file:
  #      - ./web/web.env
  #   # volumes:
  #   #   - appdata:/var/www
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - frontend
  #     - backend
  #   ports:
  #     - target: 4000
  #       published: 5663

  postgre:
    image: postgres:latest
    container_name: postgredb
    restart: unless-stopped
    env_file:
      - ./postgre/postgre.env
    # volumes:
      # - postgredbdata:/data/db
    networks:
      - backend

  # mongo:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: unless-stopped
  #   command: mongod --auth
  #   env_file:
  #     - ./mongo/mongo.env
  #   volumes:
  #     - ./mongo/flask_user_init.js:/docker-entrypoint-initdb.d/flask_user_init.js
  #     - mongodbdata:/data/db
  #   networks:
  #     - backend
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  postgredbdata:
    driver: local
  