version: '3.9'
services:
  flask:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    env_file:
       - ./web/web.env
    volumes:
      - appdata:/media
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    ports:
      - target: 4000
        published: 5663
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  appdata:
    driver: local
  